# cnn_iris



In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
# from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dense, Conv1D, Flatten

In [ ]:
!wget https://raw.githubusercontent.com/dhrim/hongik_2021/master/material/deep_learning/iris_with_category_index.csv
  

--2020-06-22 09:47:15--  https://raw.githubusercontent.com/dhrim/hongik_2021/master/material/deep_learning/iris_with_category_index.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2218 (2.2K) [text/plain]
Saving to: ‘iris_with_category_index.csv’

iris_with_category_ 100%[===================>]   2.17K  --.-KB/s    in 0s      

2020-06-22 09:47:16 (40.8 MB/s) - ‘iris_with_category_index.csv’ saved [2218/2218]



In [ ]:
iris = pd.read_csv("iris_with_category_index.csv")
iris.head()

septal_length  septal_width  petal_length  petal_width  class
0            6.4           2.8           5.6          2.2      2
1            5.0           2.3           3.3          1.0      1
2            4.9           2.5           4.5          1.7      2
3            4.9           3.1           1.5          0.1      0
4            5.7           3.8           1.7          0.3      0

In [ ]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 5)
[[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]]


In [ ]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

train_x = np.reshape(train_x, (100, 4, 1))  # ADD
test_x = np.reshape(test_x, (20, 4, 1))     # ADD

print(train_x.shape)  # ADD
print(test_x.shape)   # ADD


(100, 4)
(100, 1)
(20, 4)
(20, 1)
(100, 4, 1)
(20, 4, 1)


In [ ]:
model = keras.Sequential()
model.add(Conv1D(4, 3, activation='relu', input_shape=(4,1))) # ADD
model.add(Flatten())  # ADD
# model.add(Dense(10, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu')) # modify
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation="softmax")) # 1이 아니고 클래스 수 3이다

model.compile(optimizer="SGD", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

model.fit(train_x, train_y, epochs=1000, verbose=0, batch_size=20)

loss, acc = model.evaluate(test_x, test_y)
print("loss=", loss)
print("acc=", acc)


Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 2, 4)              16        
_________________________________________________________________
flatten (Flatten)            (None, 8)                 0         
_________________________________________________________________
dense (Dense)                (None, 10)                90        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 249
Trainable params: 249
Non-trainable params: 0
_________________________________________________________________
20/20 [==============================] - 0s

In [ ]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.9934524e-01 6.1813614e-04 3.6557609e-05]
 [1.2958698e-03 9.6958524e-01 2.9118808e-02]
 [9.9341762e-01 6.1620730e-03 4.2034150e-04]
 [1.4348680e-04 9.8500687e-01 1.4849618e-02]
 [9.9949586e-01 4.7605578e-04 2.8174120e-05]
 [9.9971384e-01 2.7214689e-04 1.3897259e-05]
 [9.9980062e-01 1.9013435e-04 9.3186991e-06]
 [9.9972719e-01 2.5908751e-04 1.3659822e-05]
 [1.4157445e-03 9.7395962e-01 2.4624581e-02]
 [9.9901295e-01 9.2875632e-04 5.8288133e-05]
 [4.1376031e-04 5.2541357e-01 4.7417268e-01]
 [1.3275958e-04 9.8543084e-01 1.4436406e-02]
 [9.9876261e-01 1.1683562e-03 6.9022513e-05]
 [1.6335589e-04 9.8887123e-03 9.8994792e-01]
 [9.9947315e-01 4.9705466e-04 2.9811974e-05]
 [1.9978684e-04 9.5023769e-01 4.9562540e-02]
 [1.7898460e-04 9.8373079e-01 1.6090259e-02]
 [9.9884963e-01 1.0754750e-03 7.4863186e-05]
 [9.9936849e-01 5.9564342e-04 3.5865480e-05]
 [2.5258967e-04 9.8151684e-01 1.8230600e-02]]
[0 1 0 1 0 0 0 0 1 0 1 1 0 2 0 1 1 0 0 1]
