# Quiz.
```
[ 0 1 2 0 1 2 0 1 2] 배열을

[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
배열로 변환
```


In [ ]:
import numpy as np

a = np.array([0,1,2,0,1,2,0,1,2])
b = np.zeros((a.shape[0],3))

# b[:,0] = (a==0)*1.0
# b[:,1] = (a==1)*1.0
# b[:,2] = (a==2)*1.0
for i in range(3):
  b[:,i] = (a==i)*1.0
  
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import tensorflow.keras.utils

a = np.array([0,1,2,0,1,2,0,1,2])
b = tensorflow.keras.utils.to_categorical(a)

print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
a = np.array([0,1,2,0,1,2,0,1,2])

categories = np.unique(a)
print(categories)

eye = np.eye(len(categories))
b = eye[a]

print(b)


[0 1 2]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Quiz

# Quiz.
```
[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
[ 0 0 0 ]
배열을

[ 0 1 2 0 1 2 0 1 2] 
배열로 변환
```


In [ ]:
import numpy as np

a = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1],
    [1,0,0],
    [0,1,0],
    [0,0,1],
    [1,0,0],
    [0,1,0],
    [0,0,1]    
])

b = np.argmax(a, axis=1)

print(b)

[0 1 2 0 1 2 0 1 2]


# Quiz. 

임의의 데이터를 6:4로 나눈다.

[1 2 3 4 ... 9 0]을
[ 1 2 .. 6], [ 7 8 .. 0]으로 나눈다.


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,0])

split_index = int(a.shape[0]*0.6)

b1 = a[0:split_index]
b2 = a[split_index:]

print(b1)
print(b2)

[1 2 3 4 5 6]
[7 8 9 0]


# Quiz. 

임의의 데이터를 6:4로 나눈다.
```
[ 1 0 0 ]
[ 2 0 0 ]
...
[ 0 0 0 ]를

[ 1 0 0 ]
...
[ 6 0 0 ]와

[ 7 0 0 ]
...
[ 0 0 0 ]
```

In [ ]:
a = np.zeros((10,3))
a[:,0] = [1,2,3,4,5,6,7,8,9,0]


split_index = int(a.shape[0]*0.6)

b1 = a[0:split_index]
b2 = a[split_index:]

print(b1)
print(b2)


[[1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]]
[[7. 0. 0.]
 [8. 0. 0.]
 [9. 0. 0.]
 [0. 0. 0.]]


# Quiz

```
a = [0,1,2,3,4,5]
b = [0,2,4,6,8,10]
```

a와 b를 동시에 섞는다.
```
[3 5  1  0 4 2]
[6 10 2 0 8 4]
```


In [ ]:
a = np.arange(10)
b = np.arange(10)*2

i = np.arange(10)
np.random.shuffle(i)

a = a[i]
b = b[i]
print(a)
print(b)

[1 6 2 9 4 7 3 5 8 0]
[ 2 12  4 18  8 14  6 10 16  0]


# Quiz

다음과 클래스 이름 어레이로 클래스 인덱스 어레이 생성
```
["cat", "cat", "dog", "cat", "horse", "horse", "dog", "cat"]

cat : 0
dog : 1
horse : 2

[0 0 1 0 2 2 1 0]
```

In [ ]:
import numpy as np

category_names = np.array(
    ["cat", "cat", "dog", "cat", "horse", "horse", "dog", "cat"]
)

labels, indexes = np.unique(category_names, return_inverse=True)  
print(labels)
print(indexes)

['cat' 'dog' 'horse']
[0 0 1 0 2 2 1 0]
